name: wallpaper
description: Simple wallpaper flutter

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.7
  flutter_staggered_grid_view: ^0.3.0
  image_picker: ^0.6.7+4
  path_provider: ^1.6.11
  permission_handler: ^5.0.1+1
  sqflite: ^1.3.1
  firebase_storage: ^3.1.6
  uuid: ^2.2.0
  rxdart: ^0.24.1
  intl: ^0.18.0
  http: ^0.12.1
  cached_network_image: ^2.2.0+1
  tuple: ^1.0.3
  sqlbrite: ^1.4.0
  disposebag: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/picture.png
    - assets/drawer_header_image.jpg
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/NunitoSans-Regular.ttf
